<div class="post" id="post-1">
    <h3>Lorem Ipsum</h3>
    <div class="post-inner">
        <div class="date-tab"><span class="month">Prosinec</span><span class="day">13</span></div>
        <div class="thumbnail"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit suscipit erat. Nulla interdum augue sit amet ipsum. Pellentesque venenatis ornare nisi. In quis risus. Pellentesque interdum vulputate erat. Duis dignissim laoreet arcu. Proin pellentesque augue id metus. Ut sed nisi at elit egestas consectetur. Aenean rhoncus. Pellentesque ac magna. Maecenas tincidunt.</p>
    </div>
    <div class="meta">Kategorie Test |  5 komentářů</div>
</div>