<?php

/**
 * Default Layout
 *
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype()
?>

<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php
		echo $this->headTitle();
	    echo $this->headScript();
	    echo $this->headStyle();
	    echo $this->headLink();
	    ?>
	</head>

<body><div id="container">
  <div id="search">
    <form method="get" id="searchform" action="index.php">
      <input type="text" value="" name="s" id="s" class="txtField" />
      <input type="hidden" name="search" value="1" />
      <input type="submit" id="searchsubmit" class="btnSearch" value="Hledej &raquo;" />
    </form>
  </div>
  <div id="menu-holder"><ul id="menu">
  <li id="home"><a href="index.php">Home</a></li>
  <li id="about"><a href="#">About</a></li>
  <li id="archives"><a href="index.php?archiv">Archives</a></li>
</ul>
</div>
  <div id="title">
    <h2><a href="/"><?php echo $this->placeholder('WebName'); ?></a></h2>
  Pobudové z Brodu</div>
</div>
<div id="content">
  <div class="col01"><?php echo $this->layout()->content ?></div>
  <div class="col02">
    <div class="recent-posts">
            <ul>
    <li><a href="http://localhost/landy/?p=1">Hello world!<br />
    <span class="listMeta">6:00 pm, September 27, 2008</span></a></li>
    </ul>
        </div>
    <div class="postit-bottom"></div>
    <div class="categories-upper"></div>
<div class="categories">
  <ul>
        <li class="cat-item cat-item-1"><a href="http://localhost/landy/?cat=1" title="View all posts filed under Uncategorized">Uncategorized</a>
</li>
  </ul>
</div>
<div class="categories-btm"></div>
<div class="links">
<ul>
<li><a href="http://wordpress.org/development/">Development Blog</a></li>
<li><a href="http://codex.wordpress.org/">Documentation</a></li>
<li><a href="http://wordpress.org/extend/plugins/">Plugins</a></li>
<li><a href="http://wordpress.org/extend/ideas/">Suggest Ideas</a></li>
<li><a href="http://wordpress.org/support/">Support Forum</a></li>
<li><a href="http://wordpress.org/extend/themes/">Themes</a></li>
<li><a href="http://planet.wordpress.org/">WordPress Planet</a></li>
</ul>
</div>
<div class="side-meta">
  <ul>
    <li><a href="http://localhost/landy/wp-admin/">Site Admin</a></li>    <li>
      <a href="http://localhost/landy/wp-login.php?action=logout">Log out</a>    </li>
    <li><a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional">Valid <abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a></li>
    <li><a href="http://gmpg.org/xfn/"><abbr title="XHTML Friends Network">XFN</abbr></a></li>
    <li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress</a></li>
      </ul>
</div>  </div>
  <br clear="all" />
</div>
<div id="footer-holder">
  <div class="footer"></div>
  <div class="txt">
                <p>This is an example of a WordPress page, you could edit this to put information about yourself or your site so readers know where you are coming from. You can create as many pages like this one or sub-pages as you like and manage all of your content inside of WordPress.</p>
          </div>
  <span class="smashing"><a href="http://jobs.smashingmagazine.com">Smashing Magazine</a></span> <span class="rss"><a href="http://localhost/landy/?feed=rss2">RSS</a></span></div>
</body></html>